require:
  - rubocop-rails

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Layout/LineLength:
  Max: 120

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
    - 'test/**/*'

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/*'
    - 'test/**/*'

Rails:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/Lambda:
  Enabled: true
  EnforcedStyle: 'literal'

Style/NumericLiterals:
  Enabled: false

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true
